name = input('Enter your name: ')
company = input('Enter your company: ')
title = input('Enter your title: ')
phone = input('Enter your phone: ')
email = input('Enter your email: ')
print('*****************************************')
print('姓名：',name,sep='')
print('公司：' + company)
print('职位：%s' % title)
print('电话：',phone,sep='')
print('E-mail:',email,sep='')
print('*****************************************')